USE test_db;

ALTER TABLE `users` DROP PRIMARY KEY ;

ALTER TABLE `users` MODIFY id INT AUTO_INCREMENT;

ALTER  TABLE `users` ADD CONSTRAINT PRIMARY KEY `pk_users`(id);

ALTER TABLE users MODIFY `username` VARCHAR(50) UNIQUE ;